const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('deck', {
  runAgent: (cfg) => ipcRenderer.invoke('agent-run', cfg),
  aiGenerate: (prompt, model, cwd) => ipcRenderer.invoke('ai-generate', { prompt, model, cwd }),
  stopAgent: (runId) => ipcRenderer.invoke('agent-stop', runId),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  exec: (command, cwd) => ipcRenderer.invoke('exec', { command, cwd }),
  gitRepos: (root) => ipcRenderer.invoke('git-repos', root),
  gitStatus: (repo) => ipcRenderer.invoke('git-status', repo),
  gitCmd: (repo, op, arg) => ipcRenderer.invoke('git-cmd', { repo, op, arg }),
  gitStream: (repo, op, arg, streamId) => ipcRenderer.invoke('git-stream', { repo, op, arg, streamId }),
  onGitStream: (cb) => ipcRenderer.on('git-stream-data', (_e, p) => cb(p)),
  gitBranches: (repo) => ipcRenderer.invoke('git-branches', repo),
  gitLog: (repo, limit) => ipcRenderer.invoke('git-log', { repo, limit }),
  gitDiff: (repo, opts) => ipcRenderer.invoke('git-diff', { repo, ...opts }),
  gitRemotes: (repo) => ipcRenderer.invoke('git-remotes', repo),
  gitIgnoreLoveai: (repo) => ipcRenderer.invoke('git-ignore-loveai', repo),
  gitRemoteCmd: (repo, op, name, url) => ipcRenderer.invoke('git-remote-cmd', { repo, op, name, url }),
  ciList: (repo) => ipcRenderer.invoke('ci-list', repo),
  ciScaffold: (repo) => ipcRenderer.invoke('ci-scaffold', repo),
  ciStatus: (repo) => ipcRenderer.invoke('ci-status', repo),
  prList: (repo) => ipcRenderer.invoke('pr-list', repo),
  prCreate: (repo, data) => ipcRenderer.invoke('pr-create', { repo, ...data }),
  prReview: (repo, number, action, body) => ipcRenderer.invoke('pr-review', { repo, number, action, body }),
  prMerge: (repo, number, method) => ipcRenderer.invoke('pr-merge', { repo, number, method }),
  prDiff: (repo, number, base, head) => ipcRenderer.invoke('pr-diff', { repo, number, base, head }),
  prConflictCheck: (repo, base, head) => ipcRenderer.invoke('pr-conflict-check', { repo, base, head }),
  prStartMerge: (repo, base, head) => ipcRenderer.invoke('pr-start-merge', { repo, base, head }),
  prAbortMerge: (repo) => ipcRenderer.invoke('pr-abort-merge', repo),
  prView: (repo, number) => ipcRenderer.invoke('pr-view', { repo, number }),
  prComment: (repo, number, body) => ipcRenderer.invoke('pr-comment', { repo, number, body }),
  termStart: (termId, cwd, cols, rows, shell) => ipcRenderer.invoke('term-start', { termId, cwd, cols, rows, shell }),
  termInput: (termId, data) => ipcRenderer.invoke('term-input', { termId, data }),
  termResize: (termId, cols, rows) => ipcRenderer.invoke('term-resize', { termId, cols, rows }),
  termKill: (termId) => ipcRenderer.invoke('term-kill', termId),
  onTermData: (cb) => ipcRenderer.on('term-data', (_e, payload) => cb(payload)),
  fsList: (root, dir) => ipcRenderer.invoke('fs-list', { root, dir }),
  fsRead: (root, file, theme) => ipcRenderer.invoke('fs-read', { root, file, theme }),
  fsWrite: (root, file, content) => ipcRenderer.invoke('fs-write', { root, file, content }),
  fsCreate: (root, dir, rel, isDir) => ipcRenderer.invoke('fs-create', { root, dir, rel, isDir }),
  fsRename: (root, from, to) => ipcRenderer.invoke('fs-rename', { root, from, to }),
  fsDelete: (root, target) => ipcRenderer.invoke('fs-delete', { root, target }),
  fsHighlight: (content, lang, theme) => ipcRenderer.invoke('fs-highlight', { content, lang, theme }),
  mcpList: (projectDir) => ipcRenderer.invoke('mcp-list', projectDir),
  skillsList: (projectDir) => ipcRenderer.invoke('skills-list', projectDir),
  commandsList: (projectDir) => ipcRenderer.invoke('commands-list', projectDir),
  skillRead: (fp) => ipcRenderer.invoke('skill-read', fp),
  skillCreate: (data) => ipcRenderer.invoke('skill-create', data),
  skillSave: (fp, content) => ipcRenderer.invoke('skill-save', { fp, content }),
  skillDelete: (fp) => ipcRenderer.invoke('skill-delete', fp),
  cliVersion: () => ipcRenderer.invoke('cli-version'),
  pipelineScan: (cwd) => ipcRenderer.invoke('pipeline-scan', cwd),
  pipelineRead: (cwd) => ipcRenderer.invoke('pipeline-read', cwd),
  pipelineWrite: (cwd, name, content) => ipcRenderer.invoke('pipeline-write', { cwd, name, content }),
  pipelineReset: (cwd) => ipcRenderer.invoke('pipeline-reset', cwd),
  indexStatus: (cwd) => ipcRenderer.invoke('index-status', cwd),
  indexMark: (cwd) => ipcRenderer.invoke('index-mark', cwd),
  symbolBuild: (cwd) => ipcRenderer.invoke('symbol-build', cwd),
  symbolEnsure: (cwd) => ipcRenderer.invoke('symbol-ensure', cwd),
  symbolWatch: (cwd) => ipcRenderer.invoke('symbol-watch', cwd),
  onSymbolUpdated: (cb) => ipcRenderer.on('symbol-updated', (_e, p) => cb(p)),
  retrieveContext: (cwd, query, k, withContent) => ipcRenderer.invoke('retrieve-context', { cwd, query, k, withContent }),
  authStatus: () => ipcRenderer.invoke('auth-status'),
  planUsage: () => ipcRenderer.invoke('plan-usage'),
  sessionsList: () => ipcRenderer.invoke('sessions-list'),
  sessionLoad: (sessionId) => ipcRenderer.invoke('session-load', sessionId),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  authLogin: () => ipcRenderer.invoke('auth-login'),
  authLogout: () => ipcRenderer.invoke('auth-logout'),
  fileToPath: (file) => { try { return webUtils.getPathForFile(file); } catch { return file.path || null; } },
  clipboardRead: () => ipcRenderer.invoke('clipboard-read'),
  clipboardWrite: (text) => ipcRenderer.invoke('clipboard-write', text),
  onAgentEvent: (cb) => ipcRenderer.on('agent-event', (_e, payload) => cb(payload))
});
