const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('deck', {
  runAgent: (cfg) => ipcRenderer.invoke('agent-run', cfg),
  stopAgent: (runId) => ipcRenderer.invoke('agent-stop', runId),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  exec: (command, cwd) => ipcRenderer.invoke('exec', { command, cwd }),
  gitRepos: (root) => ipcRenderer.invoke('git-repos', root),
  gitStatus: (repo) => ipcRenderer.invoke('git-status', repo),
  gitCmd: (repo, op, arg) => ipcRenderer.invoke('git-cmd', { repo, op, arg }),
  termStart: (termId, cwd, cols, rows, shell) => ipcRenderer.invoke('term-start', { termId, cwd, cols, rows, shell }),
  termInput: (termId, data) => ipcRenderer.invoke('term-input', { termId, data }),
  termResize: (termId, cols, rows) => ipcRenderer.invoke('term-resize', { termId, cols, rows }),
  termKill: (termId) => ipcRenderer.invoke('term-kill', termId),
  onTermData: (cb) => ipcRenderer.on('term-data', (_e, payload) => cb(payload)),
  fsList: (root, dir) => ipcRenderer.invoke('fs-list', { root, dir }),
  fsRead: (root, file, theme) => ipcRenderer.invoke('fs-read', { root, file, theme }),
  fsWrite: (root, file, content) => ipcRenderer.invoke('fs-write', { root, file, content }),
  fsHighlight: (content, lang, theme) => ipcRenderer.invoke('fs-highlight', { content, lang, theme }),
  mcpList: (projectDir) => ipcRenderer.invoke('mcp-list', projectDir),
  skillsList: (projectDir) => ipcRenderer.invoke('skills-list', projectDir),
  commandsList: (projectDir) => ipcRenderer.invoke('commands-list', projectDir),
  skillRead: (fp) => ipcRenderer.invoke('skill-read', fp),
  skillCreate: (data) => ipcRenderer.invoke('skill-create', data),
  skillSave: (fp, content) => ipcRenderer.invoke('skill-save', { fp, content }),
  skillDelete: (fp) => ipcRenderer.invoke('skill-delete', fp),
  cliVersion: () => ipcRenderer.invoke('cli-version'),
  pipelineScan: (cwd) => ipcRenderer.invoke('pipeline-scan', cwd),
  pipelineRead: (cwd) => ipcRenderer.invoke('pipeline-read', cwd),
  pipelineReset: (cwd) => ipcRenderer.invoke('pipeline-reset', cwd),
  indexStatus: (cwd) => ipcRenderer.invoke('index-status', cwd),
  indexMark: (cwd) => ipcRenderer.invoke('index-mark', cwd),
  authStatus: () => ipcRenderer.invoke('auth-status'),
  planUsage: () => ipcRenderer.invoke('plan-usage'),
  sessionsList: () => ipcRenderer.invoke('sessions-list'),
  sessionLoad: (sessionId) => ipcRenderer.invoke('session-load', sessionId),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  authLogin: () => ipcRenderer.invoke('auth-login'),
  authLogout: () => ipcRenderer.invoke('auth-logout'),
  fileToPath: (file) => { try { return webUtils.getPathForFile(file); } catch { return file.path || null; } },
  onAgentEvent: (cb) => ipcRenderer.on('agent-event', (_e, payload) => cb(payload))
});
