const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('deck', {
  runAgent: (cfg) => ipcRenderer.invoke('agent-run', cfg),
  aiGenerate: (prompt, model, cwd) => ipcRenderer.invoke('ai-generate', { prompt, model, cwd }),
  stopAgent: (runId) => ipcRenderer.invoke('agent-stop', runId),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  pickFiles: (images) => ipcRenderer.invoke('pick-files', { images }),
  exec: (command, cwd) => ipcRenderer.invoke('exec', { command, cwd }),
  gitRepos: (root) => ipcRenderer.invoke('git-repos', root),
  gitStatus: (repo) => ipcRenderer.invoke('git-status', repo),
  gitCmd: (repo, op, arg) => ipcRenderer.invoke('git-cmd', { repo, op, arg }),
  gitStream: (repo, op, arg, streamId) => ipcRenderer.invoke('git-stream', { repo, op, arg, streamId }),
  onGitStream: (cb) => ipcRenderer.on('git-stream-data', (_e, p) => cb(p)),
  gitBranches: (repo) => ipcRenderer.invoke('git-branches', repo),
  gitLog: (repo, limit) => ipcRenderer.invoke('git-log', { repo, limit }),
  gitDiff: (repo, opts) => ipcRenderer.invoke('git-diff', { repo, ...opts }),
  gitRemotes: (repo) => ipcRenderer.invoke('git-remotes', repo),
  gitIgnoreLoveai: (repo) => ipcRenderer.invoke('git-ignore-loveai', repo),
  gitRemoteCmd: (repo, op, name, url) => ipcRenderer.invoke('git-remote-cmd', { repo, op, name, url }),
  gitRepoRoot: (cwd) => ipcRenderer.invoke('git-repo-root', cwd),
  checkpointCreate: (repo) => ipcRenderer.invoke('checkpoint-create', repo),
  checkpointTouched: (repo, ref, baselineUntracked) => ipcRenderer.invoke('checkpoint-touched', { repo, ref, baselineUntracked }),
  checkpointDiff: (repo, ref, file) => ipcRenderer.invoke('checkpoint-diff', { repo, ref, file }),
  checkpointRevert: (repo, ref, files) => ipcRenderer.invoke('checkpoint-revert', { repo, ref, files }),
  checkpointsLoad: (repo) => ipcRenderer.invoke('checkpoints-load', repo),
  checkpointsSave: (repo, list) => ipcRenderer.invoke('checkpoints-save', { repo, list }),
  ciList: (repo) => ipcRenderer.invoke('ci-list', repo),
  ciScaffold: (repo) => ipcRenderer.invoke('ci-scaffold', repo),
  ciStatus: (repo) => ipcRenderer.invoke('ci-status', repo),
  prList: (repo) => ipcRenderer.invoke('pr-list', repo),
  prCreate: (repo, data) => ipcRenderer.invoke('pr-create', { repo, ...data }),
  prReview: (repo, number, action, body) => ipcRenderer.invoke('pr-review', { repo, number, action, body }),
  prMerge: (repo, number, method) => ipcRenderer.invoke('pr-merge', { repo, number, method }),
  prDiff: (repo, number, base, head) => ipcRenderer.invoke('pr-diff', { repo, number, base, head }),
  prConflictCheck: (repo, base, head) => ipcRenderer.invoke('pr-conflict-check', { repo, base, head }),
  prStartMerge: (repo, base, head) => ipcRenderer.invoke('pr-start-merge', { repo, base, head }),
  prAbortMerge: (repo) => ipcRenderer.invoke('pr-abort-merge', repo),
  prView: (repo, number) => ipcRenderer.invoke('pr-view', { repo, number }),
  prComment: (repo, number, body) => ipcRenderer.invoke('pr-comment', { repo, number, body }),
  termStart: (termId, cwd, cols, rows, shell) => ipcRenderer.invoke('term-start', { termId, cwd, cols, rows, shell }),
  termInput: (termId, data) => ipcRenderer.invoke('term-input', { termId, data }),
  termResize: (termId, cols, rows) => ipcRenderer.invoke('term-resize', { termId, cols, rows }),
  termKill: (termId) => ipcRenderer.invoke('term-kill', termId),
  onTermData: (cb) => ipcRenderer.on('term-data', (_e, payload) => cb(payload)),
  fsList: (root, dir) => ipcRenderer.invoke('fs-list', { root, dir }),
  fsRead: (root, file, theme) => ipcRenderer.invoke('fs-read', { root, file, theme }),
  fsReadImage: (root, file) => ipcRenderer.invoke('fs-read-image', { root, file }),
  fsWrite: (root, file, content) => ipcRenderer.invoke('fs-write', { root, file, content }),
  memoryList: (cwd) => ipcRenderer.invoke('memory-list', { cwd }),
  memoryReindex: (cwd) => ipcRenderer.invoke('memory-reindex', { cwd }),
  fsCreate: (root, dir, rel, isDir) => ipcRenderer.invoke('fs-create', { root, dir, rel, isDir }),
  fsRename: (root, from, to) => ipcRenderer.invoke('fs-rename', { root, from, to }),
  fsDelete: (root, target) => ipcRenderer.invoke('fs-delete', { root, target }),
  fsCopy: (root, from, to) => ipcRenderer.invoke('fs-copy', { root, from, to }),
  fsImport: (root, from, to) => ipcRenderer.invoke('fs-import', { root, from, to }),
  fsHighlight: (content, lang, theme) => ipcRenderer.invoke('fs-highlight', { content, lang, theme }),
  mcpList: (projectDir) => ipcRenderer.invoke('mcp-list', projectDir),
  skillsList: (projectDir) => ipcRenderer.invoke('skills-list', projectDir),
  commandsList: (projectDir) => ipcRenderer.invoke('commands-list', projectDir),
  skillRead: (fp) => ipcRenderer.invoke('skill-read', fp),
  skillCreate: (data) => ipcRenderer.invoke('skill-create', data),
  skillSave: (fp, content) => ipcRenderer.invoke('skill-save', { fp, content }),
  skillDelete: (fp) => ipcRenderer.invoke('skill-delete', fp),
  cliVersion: () => ipcRenderer.invoke('cli-version'),
  pipelineScan: (cwd) => ipcRenderer.invoke('pipeline-scan', cwd),
  pipelineRead: (cwd) => ipcRenderer.invoke('pipeline-read', cwd),
  pipelineWrite: (cwd, name, content) => ipcRenderer.invoke('pipeline-write', { cwd, name, content }),
  pipelineReset: (cwd) => ipcRenderer.invoke('pipeline-reset', cwd),
  indexStatus: (cwd) => ipcRenderer.invoke('index-status', cwd),
  indexMark: (cwd) => ipcRenderer.invoke('index-mark', cwd),
  symbolBuild: (cwd) => ipcRenderer.invoke('symbol-build', cwd),
  symbolEnsure: (cwd) => ipcRenderer.invoke('symbol-ensure', cwd),
  symbolWatch: (cwd) => ipcRenderer.invoke('symbol-watch', cwd),
  onSymbolUpdated: (cb) => ipcRenderer.on('symbol-updated', (_e, p) => cb(p)),
  retrieveContext: (cwd, query, k, withContent) => ipcRenderer.invoke('retrieve-context', { cwd, query, k, withContent }),
  retrieveSymbols: (cwd, query, budget, comments) => ipcRenderer.invoke('retrieve-symbols', { cwd, query, budget, comments }),
  regressionImpact: (cwd, prompt) => ipcRenderer.invoke('regression-impact', { cwd, prompt }),
  codegraphStatus: (cwd) => ipcRenderer.invoke('codegraph-status', cwd),
  codegraphBuild: (cwd) => ipcRenderer.invoke('codegraph-build', cwd),
  onCodegraphProgress: (cb) => ipcRenderer.on('codegraph-progress', (_e, p) => cb(p)),
  onCodegraphUpdated: (cb) => ipcRenderer.on('codegraph-updated', (_e, p) => cb(p)),
  vectorStatus: (cwd) => ipcRenderer.invoke('vector-status', cwd),
  vectorBuild: (cwd) => ipcRenderer.invoke('vector-build', cwd),
  vectorQuery: (cwd, query, k) => ipcRenderer.invoke('vector-query', { cwd, query, k }),
  onVectorProgress: (cb) => ipcRenderer.on('vector-progress', (_e, p) => cb(p)),
  onVectorUpdated: (cb) => ipcRenderer.on('vector-updated', (_e, p) => cb(p)),
  planContext: (cwd, issue) => ipcRenderer.invoke('plan-context', { cwd, issue }),
  planGenerate: (cwd, issue, model, effort) =>
    ipcRenderer.invoke('plan-generate', { cwd, issue, model, effort }),
  authStatus: () => ipcRenderer.invoke('auth-status'),
  effortLevels: () => ipcRenderer.invoke('effort-levels'),
  planUsage: () => ipcRenderer.invoke('plan-usage'),
  sessionsList: () => ipcRenderer.invoke('sessions-list'),
  sessionLoad: (sessionId) => ipcRenderer.invoke('session-load', sessionId),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  authLogin: () => ipcRenderer.invoke('auth-login'),
  authLogout: () => ipcRenderer.invoke('auth-logout'),
  fileToPath: (file) => { try { return webUtils.getPathForFile(file); } catch { return file.path || null; } },
  clipboardRead: () => ipcRenderer.invoke('clipboard-read'),
  clipboardWrite: (text) => ipcRenderer.invoke('clipboard-write', text),
  onAgentEvent: (cb) => ipcRenderer.on('agent-event', (_e, payload) => cb(payload)),
  saasSession: () => ipcRenderer.invoke('saas-session'),
  saasLoginStart: () => ipcRenderer.invoke('saas-login-start'),
  saasLogout: () => ipcRenderer.invoke('saas-logout'),
  saasProfile: () => ipcRenderer.invoke('saas-profile'),
  saasSettingsGet: () => ipcRenderer.invoke('saas-settings-get'),
  saasSettingsSet: (s) => ipcRenderer.invoke('saas-settings-set', s),
  saasRosterGet: () => ipcRenderer.invoke('saas-roster-get'),
  saasRosterSet: (a) => ipcRenderer.invoke('saas-roster-set', a),
  listFiles: (root) => ipcRenderer.invoke('list-files', root),
  watchFiles: (root, files) => ipcRenderer.invoke('watch-files', { root, files }),
  onFileDiskChange: (cb) => ipcRenderer.on('file-disk-change', (_e, p) => cb(p)),
  saasSkillsPush: () => ipcRenderer.invoke('saas-skills-push'),
  saasSkillsPull: () => ipcRenderer.invoke('saas-skills-pull'),
  onAuthChanged: (cb) => ipcRenderer.on('auth-changed', (_e, p) => cb(p)),
  claudeSetupCheck: () => ipcRenderer.invoke('claude-setup-check')
});
